### ISSUE TITLE
Remove advanced help?

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#107]
@mateu-aguilo-bosch I'm thinking out loud. Should we keep the advanced help  -- currently the docs are a todo, which is fine, I just wonder if they'll ever be something that would be valuable for users. 

Maybe if it was easy to assign a customisable link so they would direct to help.example.com?

**Comment by e0ipso** [comment]
One of the requirements of IETF API-Problem is o provide URLs with resources explaining what the problem is, which I think is a great UX idea.

Advanced Help seemed to me a great framework to do just that since it's just adding some `*.ini` and a couple of HTMLs. Also, there is no requirement for it. If the site does not have the module enabled the is no error.

**Comment by amitaibu** [comment]
ok, lets keep it :)
