### ISSUE TITLE
Prepare for release

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#158]
@mateu-aguilo-bosch 

I'd like to suggest an approach for getting release/ RC/ Beta or whatever we decide to call it out:

I've added a "release blocker" label, so both you and I can mark freely the issues we want to tackle.
Let's time-box the effort by setting a soft limit to the end of Sep (i.e. the beginning of DrupalCon Amsterdam).

Que pensas?

**Comment by e0ipso** [comment]
:+1:

**Comment by mike-potter** [comment]
Don't mean to hijack anything, but I've got to say I am _very_ excited to see this module.  It has a very good chance of getting added to Open Atrium since it follows most all of the best practices that I've been looking for in an API helper for Drupal 7.  Great work on this guys!  Sorry I won't be at Amsterdam to celebrate the release, but will be watching drupal.org.

**Comment by e0ipso** [comment]
Thanks @mike-potter! It is very encouraging getting to hear your nice words. The goal here will be to remove the _most_ from your comment :smiley:

**Comment by e0ipso** [comment]
@amitaibu I believe that after having merged https://github.com/Gizra/restful/pull/269 we'll be ready for a release candidate. Any objections?

cc/ @mike-potter @mirzu

**Comment by amitaibu** [comment]
Cool, I'll tag `RC1`!

**Comment by amitaibu** [comment]
- https://github.com/Gizra/restful/releases/tag/7.x-1.0-rc1
- https://www.drupal.org/node/2382023

@mateu-aguilo-bosch I didn't have anything smart to say in the release notes, maybe you will have a better idea :)

**Comment by e0ipso** [comment]
> maybe you will have a better idea :)

I don't have many smart things to say, but I have silly things to say.
