### ISSUE TITLE
HAL+JSON: Curie docs

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#260]
Currently we are using a default curie URL is none passed in the plugin. We can either remove it, or maybe integrate with advanced help?

**Comment by e0ipso** [comment]
I like the idea of using advanced help, since we are (supposedly) already doing that with the fancy error handling.

Although, maybe the implementor should be the one responsible for filling this one in… There is not much we can say about their curie, right?

A possible alternative would be, provide an example module that has the necessary file structure expected by Advanced Help, but even then that won't take them very far.

**Comment by e0ipso** [comment]
Ideas? @amitaibu @mirzu

**Comment by e0ipso** [comment]
Closed in an issue purge. Please, feel free to reopen if necessary.
