### ISSUE TITLE
RESTful version 2 only gives IDs for Entity Reference fields

### ISSUE THREAD

**Issue by ness-EE** [RESTful-Drupal/restful#785]
I've just updated to version 2 (inadvertently after having to remove RESTful and reinstall due to a strange error around taxonomy terms).

Once version 2 is up and running all the fields that are made using the Entity Reference module now only return the node ID instead of all the entity's values. Can you confirm whether Entity Reference fields work correctly?

**Comment by wonder95** [comment]
Yes, I can confirm that they still work, although I suspect that there are some code differences between v1 and v2 (such as the use of annotations instead of a plugin definition), and I've only used v2. With a combination of a class for the referenced entity, a public field defined in the base entity class, and the use of the `include` parameter in the URL (see [here](https://www.youtube.com/watch?v=ND8YL76DJ3U&index=10&list=PLZOQ_ZMpYrZv8_c7jd_CkO_93-DnyVFY5)), you can get all of the needed data for an entity referenced from an entity reference field.

**Comment by e0ipso** [comment]
Thanks @wonder95 for circling back here to close the issue.
