### ISSUE TITLE
Allow settings property as required

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#897]
I could swear we had the option both in 1.x and 2.x to set `'required' => TRUE` on the `publidFieldsInfo()` so one could not post/ update without those properties (if they had access to it).

But it seems it's not there. @e0ipso am I going crazy? ;)

**Comment by e0ipso** [comment]
All the entity validation has been deferred to the https://www.drupal.org/project/entity_validator plugins.

**Comment by amitaibu** [comment]
Hmm, I think the required should be the exception as its kind of what you
would expect to get out of the box.

**Comment by RoySegall** [comment]
Wasn't that was the case from the first place? That the required will be placed in the validator plugins and no in the restful plugins?

If so - all the validation we have in shoov, for [example](https://github.com/shoov/shoov/blob/master/shoov/modules/custom/shoov_restful/plugins/restful/node/ci_builds/1.0/ShoovCiBuildsResource.class.php#L33), are redundant since no validation is being invoked.

**Comment by amitaibu** [comment]
Ok, I'll close this and just add a few words about it in the README
