### ISSUE TITLE
count results when outputting the JSON is wrong.

### ISSUE THREAD

**Issue by MaartenElsen** [RESTful-Drupal/restful#946]
When altering the query and adding extra conditions to the query, the count of the results that is being outputted in JSON is wrong. For us, I fixed it by implementing additionalHateoas() and just doing the count on the actual data that is being outputted:

function additionalHateoas($output) {
  $output['count'] = count($output['data']);
  return $output;
}

**Comment by e0ipso** [comment]
That only counts the number of items in the first page of results. Please, refer to pagination in https://www.youtube.com/playlist?list=PLZOQ_ZMpYrZv8_c7jd_CkO_93-DnyVFY5.

**Comment by PieterDC** [comment]
Thanks for that hint, @e0ipso. I'm a colleague of @MaartenElsen and I had a second look at the code. Our count was broken due to some property we used that was not available while doing a count query. That got fixed.

Now we're left with #411. But that's a different story, so feel free to close this issue.

**Comment by e0ipso** [comment]
Thanks for looping back to this.

**Comment by mjoyce91** [comment]
I'm having a similar issue. I'm using a `db_or` callback to extend OR functionality to Restful, but pagination is wrong when doing so. Here's why - say you have three nodes as follows:

`[{id:1,color:'blue',location:'US'},{id:2,color:'red',location:'US'},{id:3,color:'blue',location:'CA'}]`

If I run a db_or query to say "bring back objects `where color=blue OR location=US`", because of Drupal's normalized structure for every field, I believe distinct nodes get counted multiple times, once for if they meet the first criteria, and again if they meet the second criteria. Even though my response is the set of distinct objects, my pagination is incorrect (too high). This also has an impact on `page[size]` - if some of those duplicate results are part of that page, they get excluded, so actual page size would be less than `page[size]`.

I tried adding `-->distinct()` to my query, but that results in the count only being 1.
